In [5]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv('UserRetentionData.csv')
data

,Region,Tenure,Neighborhood,Trunk Calling Facility,Voice Messaging,Number voice messages,Minutes Peak Hrs,Calls Peak Hrs,Bill Peak Hrs,Minutes Off Peak,Calls Off Peak,Bill Off Peak,Minutes Night,Calls Night,Bill Night,Trunk Call Minutes,Trunk Calls,Trunk Call Bill,Contact for Grievances/Changes,Acct Closed?
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,SC,79,415,No,No,0,134.7,98,22.90,189.7,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False
2662,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
2663,WV,68,415,No,No,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
2664,RI,28,510,No,No,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
2665,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2666 entries, 0 to 2665
Data columns (total 20 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Region                          2666 non-null   object
 1   Tenure                          2666 non-null   int64
 2   Neighborhood                    2666 non-null   int64
 3   Trunk Calling Facility          2666 non-null   object
 4   Voice Messaging                 2666 non-null   object
 5   Number voice messages           2666 non-null   int64
 6   Minutes Peak Hrs                2666 non-null   float64
 7   Calls Peak Hrs                  2666 non-null   int64
 8   Bill Peak Hrs                   2666 non-null   float64
 9   Minutes Off Peak                2666 non-null   float64
 10  Calls Off Peak                  2666 non-null   int64
 11  Bill Off Peak                   2666 non-null   float64
 12  Minutes Night                   2666 non-null   float64
 13  Calls Night                     2666 non-null   int64
 14  Bill Night                      2666 non-null   float64
 15  Trunk Call Minutes              2666 non-null   float64
 16  Trunk Calls                     2666 non-null   int64
 17  Trunk Call Bill                 2666 non-null   float64
 18  Contact for Grievances/Changes  2666 non-null   int64
 19  Acct Closed?                    2666 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 398.5+ KB

In [8]:
data[['Voice Messaging','Trunk Calling Facility']] = data[['Voice Messaging','Trunk Calling Facility']].replace(['Yes','No'],[1,0])
data

,Region,Tenure,Neighborhood,Trunk Calling Facility,Voice Messaging,Number voice messages,Minutes Peak Hrs,Calls Peak Hrs,Bill Peak Hrs,Minutes Off Peak,Calls Off Peak,Bill Off Peak,Minutes Night,Calls Night,Bill Night,Trunk Call Minutes,Trunk Calls,Trunk Call Bill,Contact for Grievances/Changes,Acct Closed?
0,KS,128,415,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,SC,79,415,0,0,0,134.7,98,22.90,189.7,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False
2662,AZ,192,415,0,1,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
2663,WV,68,415,0,0,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
2664,RI,28,510,0,0,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
2665,TN,74,415,0,1,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [9]:
# data['Acct Closed?'] = data['Acct Closed?'].replace(['FALSE','TRUE'],[0,1])
# data

# data['Acct Closed?'].replace(['FALSE', 'TRUE'], [0, 1], inplace=True)
# data  

data['Acct Closed?'] = data['Acct Closed?'].astype(int)
data

,Region,Tenure,Neighborhood,Trunk Calling Facility,Voice Messaging,Number voice messages,Minutes Peak Hrs,Calls Peak Hrs,Bill Peak Hrs,Minutes Off Peak,Calls Off Peak,Bill Off Peak,Minutes Night,Calls Night,Bill Night,Trunk Call Minutes,Trunk Calls,Trunk Call Bill,Contact for Grievances/Changes,Acct Closed?
0,KS,128,415,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,OH,107,415,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,NJ,137,415,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,OH,84,408,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,OK,75,415,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,SC,79,415,0,0,0,134.7,98,22.90,189.7,68,16.12,221.4,128,9.96,11.8,5,3.19,2,0
2662,AZ,192,415,0,1,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,0
2663,WV,68,415,0,0,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,0
2664,RI,28,510,0,0,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,0
2665,TN,74,415,0,1,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,0

In [10]:
data = data.drop(['Region' , 'Neighborhood'] , axis=1)
data

,Tenure,Trunk Calling Facility,Voice Messaging,Number voice messages,Minutes Peak Hrs,Calls Peak Hrs,Bill Peak Hrs,Minutes Off Peak,Calls Off Peak,Bill Off Peak,Minutes Night,Calls Night,Bill Night,Trunk Call Minutes,Trunk Calls,Trunk Call Bill,Contact for Grievances/Changes,Acct Closed?
0,128,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,107,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,137,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,84,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,75,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,79,0,0,0,134.7,98,22.90,189.7,68,16.12,221.4,128,9.96,11.8,5,3.19,2,0
2662,192,0,1,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,0
2663,68,0,0,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,0
2664,28,0,0,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,0
2665,74,0,1,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,0

In [13]:
X1 = data.drop(['Acct Closed?'] , axis =1)
Y = data['Acct Closed?']

## Scaling the data

In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X1)
print(X)

[[0.52479339 0.         1.         ... 0.15       0.5        0.11111111]
 [0.43801653 0.         1.         ... 0.15       0.68518519 0.11111111]
 [0.56198347 0.         0.         ... 0.25       0.60925926 0.        ]
 ...
 [0.2768595  0.         0.         ... 0.2        0.47962963 0.33333333]
 [0.11157025 0.         0.         ... 0.3        0.70555556 0.22222222]
 [0.30165289 0.         1.         ... 0.2        0.68518519 0.        ]]

## Spiting data into train and test

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[0.29338843 0.         0.         ... 0.2        0.65555556 0.        ]
 [0.48760331 0.         1.         ... 0.1        0.6        0.33333333]
 [0.09917355 0.         0.         ... 0.3        0.72037037 0.22222222]
 ...
 [0.21487603 0.         0.         ... 0.1        0.54444444 0.        ]
 [0.5        0.         0.         ... 0.2        0.43518519 0.22222222]
 [0.60743802 1.         0.         ... 0.2        0.55555556 0.        ]]
[[0.24793388 0.         0.         ... 0.3        0.49074074 0.22222222]
 [0.15702479 0.         0.         ... 0.15       0.62037037 0.11111111]
 [0.37190083 1.         0.         ... 0.15       0.83518519 0.22222222]
 ...
 [0.28512397 0.         0.         ... 0.2        0.42962963 0.22222222]
 [0.29338843 0.         0.         ... 0.15       0.55925926 0.22222222]
 [0.41322314 0.         0.         ... 0.4        0.44074074 0.11111111]]
1436    0
819     0
2156    0
2645    0
390     0
       ..
1166    0
697     0
192     0
2199    0
224     0
Name: Acct Closed?, Length: 2132, dtype: int32
421     0
252     0
578     1
2630    0
262     0
       ..
1529    0
439     1
1805    0
2178    0
580     0
Name: Acct Closed?, Length: 534, dtype: int32

#  Modeling and predicted values

In [16]:
#-------------Logistic_regression---------------- 
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import mean_squared_error, r2_score
model = LogisticRegression()
model.fit(X_train, Y_train)
y_predict = model.predict(X_test)
y_predict

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [20]:
pd.DataFrame({"predict":y_predict, "Test":Y_test})

      predict  Test
421         0     0
252         0     0
578         1     1
2630        0     0
262         0     0
...       ...   ...
1529        0     0
439         0     1
1805        0     0
2178        0     0
580         0     0

[534 rows x 2 columns]

# Accuracy and Accuracy Average

In [693]:
#-------------Accuracy(when we split our data train and test as normally)---------------
#--------------------------------Method 1 (Accuracy)-------------------
# calculate true positives, true negatives, false positives, and false negatives
TP = sum([1 for p, t in zip(y_pred, Y_test) if p == t and p == 1])
TN = sum([1 for p, t in zip(y_pred, Y_test) if p == t and p == 0])
FP = sum([1 for p, t in zip(y_pred, Y_test) if p != t and p == 1])
FN = sum([1 for p, t in zip(y_pred, Y_test) if p != t and p == 0])

# print the results
print(f"True positives: {TP}")
print(f"True negatives: {TN}")
print(f"False positives: {FP}")
print(f"False negatives: {FN}")

# calculate Accuracy
Accuracy = (TP+TN)/(TP+FP+FN+TN)

# print the result
print(f"Accuracy: {Accuracy:.2f}")

True positives: 10
True negatives: 391
False positives: 64
False negatives: 69
Accuracy: 0.75

In [694]:
#-------------Accuracy(when we split our data train and test as normally)---------------
from sklearn.metrics import accuracy_score
accuracy_scores = accuracy_score(Y_test, y_pred)
print("accuracy of classification problem is:",acc)

accuracy of classification problem is: 0.7546816479400749

In [674]:
#--------------Average Accuracy(when crossvalidation method which gives more rebust output)-------------------------
  #--------------we find Average accuracy directly from the X and Y data points---------------------------
from sklearn.model_selection import cross_val_score
accs = cross_val_score(LogisticRegression(), X, Y, cv=10)
print(f'Average Accuracy: {np.mean(accs)}')

Average Accuracy: 0.8615978147616232

# Precision and Precision Average

In [675]:
#-------------Precision(when we split our data train and test as normally)---------------
#--------------------------------Method 1 (Precision)-------------------
# calculate true positives, true negatives, false positives, and false negatives
TP = sum([1 for p, t in zip(y_pred, Y_test) if p == t and p == 1])
TN = sum([1 for p, t in zip(y_pred, Y_test) if p == t and p == 0])
FP = sum([1 for p, t in zip(y_pred, Y_test) if p != t and p == 1])
FN = sum([1 for p, t in zip(y_pred, Y_test) if p != t and p == 0])

# print the results
print(f"True positives: {TP}")
print(f"True negatives: {TN}")
print(f"False positives: {FP}")
print(f"False negatives: {FN}")

# calculate precision
precision = TP / (TP + FP)

# print the result
print(f"Precision: {precision:.2f}")

True positives: 6
True negatives: 389
False positives: 68
False negatives: 71
Precision: 0.08

In [676]:
#--------------------------------Method 2 (Precision)-------------------
precision = precision_score(Y_test, y_pred)
# Print precision
print('Precision:', precision)

Precision: 0.08108108108108109

In [677]:
#--------------Average Precision(when we crossvalidation method which gives more rebust output)-------------------------
 #--------------we find average precision directly from the X and Y data points---------------------------
precision = cross_val_score(LogisticRegression(),X, Y, cv=5, scoring="precision")
print(precision)
print(f'Precision Average: {np.mean(precision)}')

[0.59259259 0.69565217 0.45833333 0.68421053 0.6       ]
Precision Average: 0.6061577252309518

# Recall and Recall Average

In [678]:
#-------------------------------(Method 1)recall--------------------------------------------------
# from sklearn.metrics import precision_score, recall_score
Recall = recall_score(Y_test, y_pred)

#Print recall
print('Recall:', Recall)

Recall: 0.07792207792207792

In [679]:
#-------------Recall(when we split our data train and test as normally)---------------
#--------------------------------Method 1 Recall)-------------------
# calculate true positives, true negatives, false positives, and false negatives
TP = sum([1 for p, t in zip(y_pred, Y_test) if p == t and p == 1])
TN = sum([1 for p, t in zip(y_pred, Y_test) if p == t and p == 0])
FP = sum([1 for p, t in zip(y_pred, Y_test) if p != t and p == 1])
FN = sum([1 for p, t in zip(y_pred, Y_test) if p != t and p == 0])

# print the results
print(f"True positives: {TP}")
print(f"True negatives: {TN}")
print(f"False positives: {FP}")
print(f"False negatives: {FN}")

# calculate Recall
recall = TP / (TP + FN)

# print the result
print(f"recall: {recall:.2f}")

True positives: 6
True negatives: 389
False positives: 68
False negatives: 71
recall: 0.08

In [680]:
#--------------Average Precision(when we crossvalidation method which gives more rebust output)-------------------------
 #--------------we find average precision directly from the X and Y data points---------------------------
recall = cross_val_score(LogisticRegression(),X, Y, cv=5, scoring="recall")
print(recall)
print(f'recall Average: {np.mean(recall)}')

[0.20512821 0.20779221 0.14285714 0.16666667 0.15384615]
recall Average: 0.17525807525807524